= About

The library `PPWCode.Vernacular.Contracts.I` is part of the .NET PPWCode project and encapsulates the _vernacular_ on contracts.

`PPWCode.Vernacular.Contracts.I` is a helper library to apply design-by-contract principles in .NET.  It was created to facilitate migrating away from https://www.microsoft.com/en-us/research/project/code-contracts[Microsoft Code Contracts], a research project that was halted.

The library contains simple helper methods to perform contract validation at run-time.  The library is annotated to help with static analysis of the C# code.

The library supports both different versions of .NET full framework and more recent .NET SDKs.


== Microsoft Code Contracts

https://www.microsoft.com/en-us/research/project/code-contracts[Microsoft Code Contracts] was an interesting Microsoft research project on Design-By-Contract for C# code.  The project focused both on static analysis of the C# code, using `Contract` statements for pre-conditions, post-conditions and invariants with an offline analyzer tool, and on run-time validation using an IL rewriter tool.

From what we understand, the researchers working on this project left Microsoft, and the project was halted, and the code was made open source.  The code is available at https://github.com/Microsoft/CodeContracts[GitHub].  There was very little community input, and in the end the project was archived in 2023.

Several of the projects that PeopleWare worked on took a dependency on Microsoft Code Contracts because it was a useful and powerful tool to increase code quality.  However, the tool was never really compatible with the Roslyn compiler after Visual Studio 2015 and with async code.  We needed an upgrade path for the code bases that relied on Code Contracts.  `PPWCode.Vernacular.Contracts.I` was born in this context.


== Support for .NET Full Framework

The builds for the .NET full framework cannot use the new C# annotations that help the nullability analysis done by the Roslyn compiler.  For this reason, these builds have a dependency on the `JetBrains.Annotations` package.  These annotations are supported by the static analysis done by both JetBrains Rider and ReSharper.


== Support for .NET SDKs

The builds for the .NET SDKs use the new C# annotations supported by the Roslyn compiler.  These builds do not have a dependency on the `JetBrains.Annotations` package.


== Development

Development of the PPWCode is done on https://github.com/peopleware/net-ppwcode-vernacular-contracts[GitHub].

Releases (both stable and pre-release) are published as https://www.nuget.org[NuGet] packages by https://www.nuget.org/profiles/PeopleWare[PeopleWare].


== License and Copyright

Copyright 2022–2025 by xref:ppwcode-net:ROOT:peopleware.adoc[PeopleWare].

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

