<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\common.props"/>

    <PropertyGroup>
        <!-- Stylecop -->
        <CodeAnalysisRuleSet>..\Analyzer.ruleset</CodeAnalysisRuleSet>

        <!-- Package README -->
        <PackageReadmeFile>..\..\README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="PPWCode.Vernacular.Exceptions.IV" />
    </ItemGroup>

</Project>
