name: CI

on:
  push:
    branches: [ "I/next" ]
  pull_request:
    branches: [ "I/next" ]

jobs:
  build-and-test:
    uses: peopleware/net-ppwcode-workflows/.github/workflows/ci-dotnet-and-full-framework-all-os.yml@main
    with:
      solution-file: PPWCode.Vernacular.Contracts.sln
