name: Publish to NuGet

on:
  push:
    tags:
      - '[IVX]+/[0-9]+.[0-9]+.[0-9]+'
      - '[IVX]+/[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  publish:
    uses: peopleware/net-ppwcode-workflows/.github/workflows/publish-dotnet-and-full-framework-all-os.yml@main
    with:
      solution-file: PPWCode.Vernacular.Contracts.sln
    secrets:
      PPWCODE_NUGET_USER: ${{ secrets.PPWCODE_NUGET_USER }}
