name: Publish to NuGet

on:
  push:
    tags:
      - '[IVX]+/[0-9]+.[0-9]+.[0-9]+'
      - '[IVX]+/[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  nuget-login:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      nuget-api-key: ${{ steps.nuget_login.outputs.NUGET_API_KEY }}
    steps:
    - name: NuGet login (OIDC for temp api key)
      uses: NuGet/login@v1
      id: nuget_login
      with:
        user: ${{ secrets.PPWCODE_NUGET_USER }}

  build-test-publish:
    needs: nuget-login
    uses: peopleware/net-ppwcode-workflows/.github/workflows/publish-dotnet-and-full-framework-all-os.yml@main
    with:
      solution-file: PPWCode.Vernacular.Contracts.sln
    secrets:
      PPWCODE_NUGET_API_KEY: ${{ needs.nuget-login.outputs.nuget-api-key }}
