<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\common-tests.props"/>

    <PropertyGroup>
        <!-- Stylecop -->
        <CodeAnalysisRuleSet>..\Analyzer-Tests.ruleset</CodeAnalysisRuleSet>

        <!-- Package -->
        <IsPackable>false</IsPackable>

        <!-- target framework -->
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <!-- project dependencies -->
        <ProjectReference Include="..\PPWCode.Vernacular.Contracts.I\PPWCode.Vernacular.Contracts.I.csproj"/>
    </ItemGroup>

</Project>
